import jsPDF from "jspdf";

type Profile = {
  full_name?: string | null;
  date_of_birth?: string | null;
  blood_type?: string | null;
  phone?: string | null;
  emergency_contact?: string | null;
  allergies?: string | null;
  medications?: string | null;
  diagnoses?: string | null;
  recent_reports?: string | null;
  notes?: string | null;
};

// Map consent field keys (used in profiles.consent_fields) to profile columns + labels.
const CONSENT_TO_FIELD: Record<string, { key: keyof Profile; label: string }> = {
  fullName: { key: "full_name", label: "Full name" },
  dateOfBirth: { key: "date_of_birth", label: "Date of birth" },
  bloodType: { key: "blood_type", label: "Blood type" },
  phone: { key: "phone", label: "Phone" },
  emergencyContact: { key: "emergency_contact", label: "Emergency contact" },
  allergies: { key: "allergies", label: "Allergies" },
  medications: { key: "medications", label: "Medications" },
  diagnoses: { key: "diagnoses", label: "Diagnoses" },
  recentReports: { key: "recent_reports", label: "Recent reports" },
  notes: { key: "notes", label: "Notes" },
};

export function downloadHealthSummaryPdf(profile: Profile, approvedFields: string[]) {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  let y = margin;

  // Header band
  doc.setFillColor(13, 59, 143); // clinical blue
  doc.rect(0, 0, pageW, 72, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("HayatBridge", margin, 32);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Health Summary for Sharing", margin, 52);

  const generated = new Date().toLocaleString();
  doc.setFontSize(9);
  doc.text(`Generated ${generated}`, pageW - margin, 52, { align: "right" });

  y = 100;
  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(profile.full_name || "Patient", margin, y);
  y += 20;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(
    "This document contains only the sections the patient has approved for sharing in their HayatBridge consent settings.",
    margin,
    y,
    { maxWidth: pageW - margin * 2 },
  );
  y += 30;

  // Fields
  doc.setTextColor(20, 20, 20);
  const orderedKeys = Object.keys(CONSENT_TO_FIELD);
  const fields = orderedKeys.filter((k) => approvedFields.includes(k));

  if (fields.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(11);
    doc.text(
      "No fields are currently approved in Consent. Approve fields in the HayatBridge app before exporting.",
      margin,
      y,
      { maxWidth: pageW - margin * 2 },
    );
  } else {
    for (const fkey of fields) {
      const spec = CONSENT_TO_FIELD[fkey];
      const value = String(profile[spec.key] ?? "").trim() || "—";

      if (y > pageH - 100) {
        doc.addPage();
        y = margin;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(13, 59, 143);
      doc.text(spec.label.toUpperCase(), margin, y);
      y += 14;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(20, 20, 20);
      const lines = doc.splitTextToSize(value, pageW - margin * 2);
      doc.text(lines, margin, y);
      y += lines.length * 14 + 12;

      // separator
      doc.setDrawColor(230, 232, 240);
      doc.line(margin, y - 6, pageW - margin, y - 6);
    }
  }

  // Footer on every page
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setDrawColor(220, 224, 235);
    doc.line(margin, pageH - 48, pageW - margin, pageH - 48);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(
      "Generated by HayatBridge for sharing · Reflects the patient's active consent settings.",
      margin,
      pageH - 32,
    );
    doc.text(`Page ${i} of ${pages}`, pageW - margin, pageH - 32, { align: "right" });
  }

  const safeName = (profile.full_name || "patient").replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  doc.save(`hayatbridge-health-summary-${safeName}-${Date.now()}.pdf`);
}
