/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessLogRouteImport } from './routes/access-log'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AllergiesRouteImport } from './routes/allergies'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiagnosesRouteImport } from './routes/diagnoses'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as HealthInfoRouteImport } from './routes/health-info'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PharmacistRouteImport } from './routes/pharmacist'
import { Route as QrRouteImport } from './routes/qr'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as TestResultsRouteImport } from './routes/test-results'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityLogsRouteImport } from './routes/admin.activity-logs'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminCliniciansRouteImport } from './routes/admin.clinicians'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as ViewPatientIdRouteImport } from './routes/view.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessLogRoute = AccessLogRouteImport.update({
  id: '/access-log',
  path: '/access-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AllergiesRoute = AllergiesRouteImport.update({
  id: '/allergies',
  path: '/allergies',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosesRoute = DiagnosesRouteImport.update({
  id: '/diagnoses',
  path: '/diagnoses',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthInfoRoute = HealthInfoRouteImport.update({
  id: '/health-info',
  path: '/health-info',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistRoute = PharmacistRouteImport.update({
  id: '/pharmacist',
  path: '/pharmacist',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResultsRoute = TestResultsRouteImport.update({
  id: '/test-results',
  path: '/test-results',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCliniciansRoute = AdminCliniciansRouteImport.update({
  id: '/clinicians',
  path: '/clinicians',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const ViewPatientIdRoute = ViewPatientIdRouteImport.update({
  id: '/view/$patientId',
  path: '/view/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-log': typeof AccessLogRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/allergies': typeof AllergiesRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/diagnoses': typeof DiagnosesRoute
  '/doctor': typeof DoctorRoute
  '/health-info': typeof HealthInfoRoute
  '/medications': typeof MedicationsRoute
  '/messages': typeof MessagesRoute
  '/pharmacist': typeof PharmacistRoute
  '/qr': typeof QrRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/test-results': typeof TestResultsRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/clinicians': typeof AdminCliniciansRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/view/$patientId': typeof ViewPatientIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-log': typeof AccessLogRoute
  '/admin-login': typeof AdminLoginRoute
  '/allergies': typeof AllergiesRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/diagnoses': typeof DiagnosesRoute
  '/doctor': typeof DoctorRoute
  '/health-info': typeof HealthInfoRoute
  '/medications': typeof MedicationsRoute
  '/messages': typeof MessagesRoute
  '/pharmacist': typeof PharmacistRoute
  '/qr': typeof QrRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/test-results': typeof TestResultsRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/clinicians': typeof AdminCliniciansRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/view/$patientId': typeof ViewPatientIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-log': typeof AccessLogRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/allergies': typeof AllergiesRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/consent': typeof ConsentRoute
  '/dashboard': typeof DashboardRoute
  '/diagnoses': typeof DiagnosesRoute
  '/doctor': typeof DoctorRoute
  '/health-info': typeof HealthInfoRoute
  '/medications': typeof MedicationsRoute
  '/messages': typeof MessagesRoute
  '/pharmacist': typeof PharmacistRoute
  '/qr': typeof QrRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/test-results': typeof TestResultsRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/clinicians': typeof AdminCliniciansRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/view/$patientId': typeof ViewPatientIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-log'
    | '/admin'
    | '/admin-login'
    | '/allergies'
    | '/appointments'
    | '/auth'
    | '/billing'
    | '/consent'
    | '/dashboard'
    | '/diagnoses'
    | '/doctor'
    | '/health-info'
    | '/medications'
    | '/messages'
    | '/pharmacist'
    | '/qr'
    | '/questionnaire'
    | '/reset-password'
    | '/setup'
    | '/test-results'
    | '/admin/activity-logs'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/clinicians'
    | '/admin/feedback'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/view/$patientId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-log'
    | '/admin-login'
    | '/allergies'
    | '/appointments'
    | '/auth'
    | '/billing'
    | '/consent'
    | '/dashboard'
    | '/diagnoses'
    | '/doctor'
    | '/health-info'
    | '/medications'
    | '/messages'
    | '/pharmacist'
    | '/qr'
    | '/questionnaire'
    | '/reset-password'
    | '/setup'
    | '/test-results'
    | '/admin/activity-logs'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/clinicians'
    | '/admin/feedback'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/view/$patientId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/access-log'
    | '/admin'
    | '/admin-login'
    | '/allergies'
    | '/appointments'
    | '/auth'
    | '/billing'
    | '/consent'
    | '/dashboard'
    | '/diagnoses'
    | '/doctor'
    | '/health-info'
    | '/medications'
    | '/messages'
    | '/pharmacist'
    | '/qr'
    | '/questionnaire'
    | '/reset-password'
    | '/setup'
    | '/test-results'
    | '/admin/activity-logs'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/clinicians'
    | '/admin/feedback'
    | '/admin/patients'
    | '/admin/reports'
    | '/admin/settings'
    | '/view/$patientId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessLogRoute: typeof AccessLogRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AllergiesRoute: typeof AllergiesRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  ConsentRoute: typeof ConsentRoute
  DashboardRoute: typeof DashboardRoute
  DiagnosesRoute: typeof DiagnosesRoute
  DoctorRoute: typeof DoctorRoute
  HealthInfoRoute: typeof HealthInfoRoute
  MedicationsRoute: typeof MedicationsRoute
  MessagesRoute: typeof MessagesRoute
  PharmacistRoute: typeof PharmacistRoute
  QrRoute: typeof QrRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  TestResultsRoute: typeof TestResultsRoute
  ViewPatientIdRoute: typeof ViewPatientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-log': {
      id: '/access-log'
      path: '/access-log'
      fullPath: '/access-log'
      preLoaderRoute: typeof AccessLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allergies': {
      id: '/allergies'
      path: '/allergies'
      fullPath: '/allergies'
      preLoaderRoute: typeof AllergiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnoses': {
      id: '/diagnoses'
      path: '/diagnoses'
      fullPath: '/diagnoses'
      preLoaderRoute: typeof DiagnosesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-info': {
      id: '/health-info'
      path: '/health-info'
      fullPath: '/health-info'
      preLoaderRoute: typeof HealthInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist': {
      id: '/pharmacist'
      path: '/pharmacist'
      fullPath: '/pharmacist'
      preLoaderRoute: typeof PharmacistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-results': {
      id: '/test-results'
      path: '/test-results'
      fullPath: '/test-results'
      preLoaderRoute: typeof TestResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinicians': {
      id: '/admin/clinicians'
      path: '/clinicians'
      fullPath: '/admin/clinicians'
      preLoaderRoute: typeof AdminCliniciansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/view/$patientId': {
      id: '/view/$patientId'
      path: '/view/$patientId'
      fullPath: '/view/$patientId'
      preLoaderRoute: typeof ViewPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCliniciansRoute: typeof AdminCliniciansRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCliniciansRoute: AdminCliniciansRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessLogRoute: AccessLogRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AllergiesRoute: AllergiesRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  ConsentRoute: ConsentRoute,
  DashboardRoute: DashboardRoute,
  DiagnosesRoute: DiagnosesRoute,
  DoctorRoute: DoctorRoute,
  HealthInfoRoute: HealthInfoRoute,
  MedicationsRoute: MedicationsRoute,
  MessagesRoute: MessagesRoute,
  PharmacistRoute: PharmacistRoute,
  QrRoute: QrRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  TestResultsRoute: TestResultsRoute,
  ViewPatientIdRoute: ViewPatientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
